### ISSUE TITLE
Agent fails to work on Python 2.7.9

### ISSUE THREAD

**Issue by StephenHynes7** [logentries/le#92] opened 2015-03-20 16:43 UTC
If you have Python 2.7.9 installed the Agent will fail communicate to Logentries over SSL
```
sudo le monitor --debug gives:

Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2525) 
Error: No response from LE, re-trying in 10s intervals 
Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2525) 
Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2525) 
Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2525)

https://www.python.org/downloads/release/python-279/

**Comment by jdgriffith** [comment] 2015-03-23 14:27
:+1:

**Comment by StephenHynes7** [comment] 2015-03-23 14:38
Seems like we aren't the only ones experiencing this [pain](https://www.google.ie/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=python%202.7.9%20ssl%20error)

**Comment by MarkLC** [comment] 2015-03-23 14:54
https://www.python.org/dev/peps/pep-0476/

**Comment by vilda** [comment] 2015-03-24 00:14
The former implementation in Python was broken. The agent fixes this by overriding code that wraps the socket in SSL. It should work as it is, but does not for some reason - looks like the new code requires certs in different format. Needs more investigation...

**Comment by vilda** [comment] 2015-03-24 14:40
Confirmed, it's the certificate file passed to httplib.HTTPSConnection

**Comment by vilda** [comment] 2015-03-24 15:42
#93

**Comment by mrud** [comment] 2015-03-24 19:11
should be closed by #93

**Closed by mrud** 2015-03-24 19:11 UTC
Labels: bug

**Comment by hehachris** [comment] 2015-03-26 06:30
when will that fix be available via yum update ?

**Comment by vilda** [comment] 2015-03-26 09:01
Later today @hehachris Need to test it before release
