### ISSUE TITLE
Agent fails to work on Python 2.7.5 CentOS 7

### ISSUE THREAD

**Issue by cprasarn** [logentries/le#160] opened 2015-12-26 10:07 UTC
If you have Python 2.7.5-34.el7 installed the Agent will fail communicate to Logentries over SSL (logentires 1.4.27)

Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2757) 
Connecting to api.logentries.com:443 
SSL error: [SSL] PEM lib (_ssl.c:2757)

**Comment by virgofx** [comment] 2016-01-06 20:26
+1 Confirmed error, all centos 7 systems broken.

**Comment by virgofx** [comment] 2016-01-06 20:37
Supressing SSL temporarily fixes the issue; however, there's definitely an issue opening a connection with the certs/private key mismatch.

See : http://stackoverflow.com/questions/30109449/what-does-sslerror-ssl-pem-lib-ssl-c2532-mean-using-the-python-ssl-libr

**Comment by n3trino** [comment] 2016-01-07 06:58
Any update on this as my Centos 7 environment doesn't work with logentries.

**Comment by cprasarn** [comment] 2016-01-07 09:47
Suppressing SSL works.  I, however, revert the python to the older version, which can be found on the rpm.pbone.net server, instead.

http://rpm.pbone.net/index.php3/stat/4/idpl/29076324/dir/centos_7/com/python-2.7.5-16.el7.x86_64.rpm.html

```
sudo rpm -i /tmp/python-libs-2.7.5-16.el7.x86_64.rpm --force
sudo rpm -i /tmp/python-2.7.5-16.el7.x86_64.rpm --force
sudo rpm -i /tmp/python-devel-2.7.5-16.el7.x86_64.rpm --force

sudo yum remove python-libs-2.7.5-34.el7
sudo yum remove python-2.7.5-34.el7
```

**Comment by vilda** [comment] 2016-01-08 23:25
Thanks Guys, sorry for the delay. I created MT #163 to fix this. It will be packaged Monday latest.

Additionally it seems like GPG package verification is fixed in 7 so it's used by default now.

**Closed by vilda** 2016-01-08 23:25 UTC

**Comment by virgofx** [comment] 2016-01-11 19:40
Thanks @vilda. Can you let us know after the RPMs are updated?

**Comment by vilda** [comment] 2016-01-12 12:30
RPMs are ready @virgofx! Please follow the instructions in `INSTALL.md`

**Comment by virgofx** [comment] 2016-01-12 16:12
Will test and confirm later today. Thank you.

**Comment by cprasarn** [comment] 2016-01-13 08:43
Still got an error.

```
$ le whoami
SSL error: [SSL] PEM lib (_ssl.c:2757)
Error: Cannot process LE request, no response

$ rpm -q logentries
logentries-1.4.28-1452267917.x86_64
```

**Comment by vilda** [comment] 2016-01-13 13:38
Works for me @cprasarn as well as for our support guys. Any idea how can be your system different? Try to remove `/etc/le/ca-certs.pem`. Also check if `/etc/pki/tls/certs/ca-bundle.crt` exists.

**Comment by virgofx** [comment] 2016-01-13 15:09
Works for me -- Version required 1.4.29

**Comment by cprasarn** [comment] 2016-01-18 02:41
I updated the logentries to the latest version--1.4.29--and it seems to work fine now without removing /etc/le/ca-certs.pem.
